name: flight-status-ml

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy=1.26
  - pandas=2.2
  - scikit-learn=1.3
  - matplotlib=3.8
  - seaborn=0.12
  - jupyterlab
  - pyarrow=12
  - tqdm
  - xgboost=1.7
  - imbalanced-learn=0.10.1
  - lxml
  - joblib

  - pip:
      - gdown==4.7.1
      - holidays==0.27
      - statsmodels==0.14.0
      - calmap==0.0.9
